language: node_js

node_js:
  - 6

branches:
  only:
  - master

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release

after_success: npm run test:coverage && ./node_modules/.bin/codecov